// Mocks generated by Mockito 5.4.6 from annotations
// in mukhlissmagasin/test/unit/cubits/caissier_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mukhlissmagasin/features/cashier/domain/entities/Client_entity.dart'
    as _i6;
import 'package:mukhlissmagasin/features/cashier/domain/entities/client_magasin_entity.dart'
    as _i3;
import 'package:mukhlissmagasin/features/cashier/domain/repositories/caissier_repository.dart'
    as _i2;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/ajouter_solde.dart'
    as _i7;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/ajouter_solde_clientcode.dart'
    as _i11;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/charger_recompenses_usecase.dart'
    as _i4;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/getclient_byuniquecode.dart'
    as _i12;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/getcurrent_magazin.dart'
    as _i10;
import 'package:mukhlissmagasin/features/cashier/domain/usecases/reclamer_recompense_usecase.dart'
    as _i9;
import 'package:mukhlissmagasin/features/profile/domain/entities/magasin_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCaissierRepository_0 extends _i1.SmartFake
    implements _i2.CaissierRepository {
  _FakeCaissierRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientMagasinEntity_1 extends _i1.SmartFake
    implements _i3.ClientMagasinEntity {
  _FakeClientMagasinEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChargerRecompensesClientResult_2 extends _i1.SmartFake
    implements _i4.ChargerRecompensesClientResult {
  _FakeChargerRecompensesClientResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeMagasinModel_3 extends _i1.SmartFake implements _i5.MagasinModel {
  _FakeMagasinModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_4 extends _i1.SmartFake implements _i6.Client {
  _FakeClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AjouterSoldeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAjouterSoldeUseCase extends _i1.Mock
    implements _i7.AjouterSoldeUseCase {
  MockAjouterSoldeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<_i3.ClientMagasinEntity> execute({
    required String? clientId,
    required String? magasinId,
    required double? montant,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #clientId: clientId,
              #magasinId: magasinId,
              #montant: montant,
            }),
            returnValue: _i8.Future<_i3.ClientMagasinEntity>.value(
              _FakeClientMagasinEntity_1(
                this,
                Invocation.method(#execute, [], {
                  #clientId: clientId,
                  #magasinId: magasinId,
                  #montant: montant,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.ClientMagasinEntity>);
}

/// A class which mocks [ChargerRecompensesClientUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChargerRecompensesClientUseCase extends _i1.Mock
    implements _i4.ChargerRecompensesClientUseCase {
  MockChargerRecompensesClientUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<_i4.ChargerRecompensesClientResult> execute({
    required String? clientId,
    required String? magasinId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #clientId: clientId,
              #magasinId: magasinId,
            }),
            returnValue: _i8.Future<_i4.ChargerRecompensesClientResult>.value(
              _FakeChargerRecompensesClientResult_2(
                this,
                Invocation.method(#execute, [], {
                  #clientId: clientId,
                  #magasinId: magasinId,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.ChargerRecompensesClientResult>);
}

/// A class which mocks [ReclamerRecompenseUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReclamerRecompenseUseCase extends _i1.Mock
    implements _i9.ReclamerRecompenseUseCase {
  MockReclamerRecompenseUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<void> execute({
    required String? clientId,
    required String? magasinId,
    required String? rewardId,
    required int? pointsRequired,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #clientId: clientId,
              #magasinId: magasinId,
              #rewardId: rewardId,
              #pointsRequired: pointsRequired,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [GetCurrentMagazin].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentMagazin extends _i1.Mock implements _i10.GetCurrentMagazin {
  MockGetCurrentMagazin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<_i5.MagasinModel> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i8.Future<_i5.MagasinModel>.value(
              _FakeMagasinModel_3(this, Invocation.method(#execute, [])),
            ),
          )
          as _i8.Future<_i5.MagasinModel>);
}

/// A class which mocks [AjouterSoldeClientcode].
///
/// See the documentation for Mockito's code generation for more information.
class MockAjouterSoldeClientcode extends _i1.Mock
    implements _i11.AjouterSoldeClientcode {
  MockAjouterSoldeClientcode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<_i3.ClientMagasinEntity> execute({
    required int? uniqueCode,
    required String? magasinId,
    required double? montant,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #uniqueCode: uniqueCode,
              #magasinId: magasinId,
              #montant: montant,
            }),
            returnValue: _i8.Future<_i3.ClientMagasinEntity>.value(
              _FakeClientMagasinEntity_1(
                this,
                Invocation.method(#execute, [], {
                  #uniqueCode: uniqueCode,
                  #magasinId: magasinId,
                  #montant: montant,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.ClientMagasinEntity>);
}

/// A class which mocks [GetclientByuniquecode].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetclientByuniquecode extends _i1.Mock
    implements _i12.GetclientByuniquecode {
  MockGetclientByuniquecode() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CaissierRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeCaissierRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.CaissierRepository);

  @override
  _i8.Future<_i6.Client> execute({required int? uniqueCode}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#uniqueCode: uniqueCode}),
            returnValue: _i8.Future<_i6.Client>.value(
              _FakeClient_4(
                this,
                Invocation.method(#execute, [], {#uniqueCode: uniqueCode}),
              ),
            ),
          )
          as _i8.Future<_i6.Client>);
}
