// Mocks generated by Mockito 5.4.6 from annotations
// in mukhlissmagasin/test/unit/usecases/cashier/ajouter_solde_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mukhlissmagasin/features/cashier/domain/entities/Client_entity.dart'
    as _i4;
import 'package:mukhlissmagasin/features/cashier/domain/entities/client_magasin_entity.dart'
    as _i2;
import 'package:mukhlissmagasin/features/cashier/domain/repositories/caissier_repository.dart'
    as _i5;
import 'package:mukhlissmagasin/features/profile/domain/entities/magasin_entity.dart'
    as _i3;
import 'package:mukhlissmagasin/features/rewards/domain/entities/reward_entity.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClientMagasinEntity_0 extends _i1.SmartFake
    implements _i2.ClientMagasinEntity {
  _FakeClientMagasinEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMagasinModel_1 extends _i1.SmartFake implements _i3.MagasinModel {
  _FakeMagasinModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_2 extends _i1.SmartFake implements _i4.Client {
  _FakeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CaissierRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaissierRepository extends _i1.Mock
    implements _i5.CaissierRepository {
  MockCaissierRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<double> getClientSolde({
    required String? clientId,
    required String? magasinId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientSolde, [], {
              #clientId: clientId,
              #magasinId: magasinId,
            }),
            returnValue: _i6.Future<double>.value(0.0),
          )
          as _i6.Future<double>);

  @override
  _i6.Future<int> getClientPoints({
    required String? clientId,
    required String? magasinId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClientPoints, [], {
              #clientId: clientId,
              #magasinId: magasinId,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i7.Reward>> getAvailableRewards({
    required String? clientId,
    required String? magasinId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableRewards, [], {
              #clientId: clientId,
              #magasinId: magasinId,
            }),
            returnValue: _i6.Future<List<_i7.Reward>>.value(<_i7.Reward>[]),
          )
          as _i6.Future<List<_i7.Reward>>);

  @override
  _i6.Future<void> claimReward({
    required String? clientId,
    required String? magasinId,
    required String? rewardId,
    required int? pointsRequired,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#claimReward, [], {
              #clientId: clientId,
              #magasinId: magasinId,
              #rewardId: rewardId,
              #pointsRequired: pointsRequired,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.ClientMagasinEntity> ajouterSoldeEtAppliquerOffres({
    required String? clientId,
    required String? magasinId,
    required double? montant,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ajouterSoldeEtAppliquerOffres, [], {
              #clientId: clientId,
              #magasinId: magasinId,
              #montant: montant,
            }),
            returnValue: _i6.Future<_i2.ClientMagasinEntity>.value(
              _FakeClientMagasinEntity_0(
                this,
                Invocation.method(#ajouterSoldeEtAppliquerOffres, [], {
                  #clientId: clientId,
                  #magasinId: magasinId,
                  #montant: montant,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ClientMagasinEntity>);

  @override
  _i6.Future<_i3.MagasinModel> currentMagazin() =>
      (super.noSuchMethod(
            Invocation.method(#currentMagazin, []),
            returnValue: _i6.Future<_i3.MagasinModel>.value(
              _FakeMagasinModel_1(this, Invocation.method(#currentMagazin, [])),
            ),
          )
          as _i6.Future<_i3.MagasinModel>);

  @override
  _i6.Future<_i2.ClientMagasinEntity> ajouterSoldeUniqueColdeAppliquerOffres({
    required int? uniqueCode,
    required String? magasinId,
    required double? montant,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ajouterSoldeUniqueColdeAppliquerOffres, [], {
              #uniqueCode: uniqueCode,
              #magasinId: magasinId,
              #montant: montant,
            }),
            returnValue: _i6.Future<_i2.ClientMagasinEntity>.value(
              _FakeClientMagasinEntity_0(
                this,
                Invocation.method(#ajouterSoldeUniqueColdeAppliquerOffres, [], {
                  #uniqueCode: uniqueCode,
                  #magasinId: magasinId,
                  #montant: montant,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ClientMagasinEntity>);

  @override
  _i6.Future<_i4.Client> getClientByCodeUnique({required int? uniqueCode}) =>
      (super.noSuchMethod(
            Invocation.method(#getClientByCodeUnique, [], {
              #uniqueCode: uniqueCode,
            }),
            returnValue: _i6.Future<_i4.Client>.value(
              _FakeClient_2(
                this,
                Invocation.method(#getClientByCodeUnique, [], {
                  #uniqueCode: uniqueCode,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.Client>);
}
